'use client';
import { FormEvent, useRef, useState } from 'react';
import { CameraIcon, LogoutIcon, PlusIcon } from '@/components/icons';
import { useApp } from '@/lib/app-context';

export default function Perfil(){
  const {state,addMeasurement,addProgressPhoto,updateProfile,logout,cloudMode,resetData,user}=useApp();
  const latest=state.measurements.at(-1); const [showMeasure,setShowMeasure]=useState(false); const [editing,setEditing]=useState(false); const [busy,setBusy]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const [name,setName]=useState(state.profile.name),[goal,setGoal]=useState(state.profile.goal),[weekly,setWeekly]=useState(state.profile.weeklyGoal);
  async function saveProfile(){await updateProfile(name,goal,weekly);setEditing(false)}
  async function addM(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const num=(k:string)=>fd.get(k)?Number(fd.get(k)):undefined;await addMeasurement({date:String(fd.get('date')),weight:num('weight'),waist:num('waist'),hip:num('hip'),thigh:num('thigh'),arm:num('arm'),abdomen:num('abdomen')});setShowMeasure(false)}
  async function photo(file?:File){if(!file)return;setBusy(true);await addProgressPhoto(file);setBusy(false)}
  return <><header className="topbar"><div><h1>Meu perfil</h1><p>Medidas, fotos e metas em um só lugar.</p></div><div className="avatar">{state.profile.name.slice(0,1).toUpperCase()}</div></header>
  <section className="card profile-hero"><div><div className="section-head" style={{marginBottom:10}}><h2>{state.profile.name}</h2><button className="text-btn" onClick={()=>setEditing(!editing)}>{editing?'Cancelar':'Editar'}</button></div>{editing?<><div className="field"><label>NOME</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field" style={{marginTop:8}}><label>OBJETIVO</label><input value={goal} onChange={e=>setGoal(e.target.value)}/></div><div className="field" style={{marginTop:8}}><label>META SEMANAL</label><input type="number" min="1" max="7" value={weekly} onChange={e=>setWeekly(Number(e.target.value))}/></div><button className="secondary-btn compact full" style={{marginTop:10}} onClick={saveProfile}>Salvar</button></>:<><p style={{color:'var(--muted)',fontSize:12,marginTop:0}}>{state.profile.goal}</p><div className="measurement-grid"><div className="measure-box"><span>Peso</span><strong>{latest?.weight??'—'} kg</strong></div><div className="measure-box"><span>Cintura</span><strong>{latest?.waist??'—'} cm</strong></div><div className="measure-box"><span>Quadril</span><strong>{latest?.hip??'—'} cm</strong></div><div className="measure-box"><span>Coxa</span><strong>{latest?.thigh??'—'} cm</strong></div></div></>}</div><div className="profile-photo">{state.photos[0]?<img src={state.photos[0].url} alt="Foto de progresso"/>:<CameraIcon size={38}/>}<span>Ver evolução</span></div></section>
  <section className="section"><div className="section-head"><h2>Medidas</h2><button className="text-btn" onClick={()=>setShowMeasure(true)}>+ Registrar</button></div><div className="card" style={{padding:14}}>{state.measurements.slice().reverse().map(m=><div className="history-row" key={m.id}><div className="date-badge"><strong>{new Date(m.date+'T12:00:00').getDate()}</strong>{new Date(m.date+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','').toUpperCase()}</div><div><h3>{m.weight??'—'} kg</h3><p>Cintura {m.waist??'—'} cm • Quadril {m.hip??'—'} cm • Coxa {m.thigh??'—'} cm</p></div></div>)}</div></section>
  <section className="section"><div className="section-head"><h2>Fotos de evolução</h2><button className="text-btn" onClick={()=>fileRef.current?.click()}>{busy?'Enviando...':'+ Adicionar'}</button></div><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>photo(e.target.files?.[0])}/>{state.photos.length?<div className="photo-grid">{state.photos.map(p=><div className="photo-tile" key={p.id}><img src={p.url} alt="Progresso"/><small>{new Date(p.date+'T12:00:00').toLocaleDateString('pt-BR')}</small></div>)}</div>:<div className="card empty">Suas fotos privadas de evolução aparecerão aqui.</div>}</section>
  <section className="section card account-card"><div><span className="account-label">CONTA</span><strong>{user?.email || (cloudMode ? 'Conta conectada' : 'Conta local neste aparelho')}</strong><small>{cloudMode ? 'Seus dados ficam sincronizados com a nuvem.' : 'Configure o Firebase para sincronizar em outros aparelhos.'}</small></div><button className="ghost-btn danger compact" onClick={logout}><LogoutIcon/>Sair da conta</button></section><section className="section"><button className="ghost-btn full danger" onClick={async()=>{if(window.confirm('Isso apagará treinos, histórico, medidas e fotos cadastrados no app. Deseja recomeçar do zero?')) await resetData();}}>Recomeçar dados do aplicativo</button></section>
  {showMeasure&&<div className="modal-backdrop" onClick={()=>setShowMeasure(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="section-head"><h2>Nova medição</h2><button className="text-btn" onClick={()=>setShowMeasure(false)}>Fechar</button></div><form onSubmit={addM}><div className="field"><label>DATA</label><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="form-grid" style={{marginTop:10}}>{[['weight','Peso (kg)'],['waist','Cintura (cm)'],['hip','Quadril (cm)'],['thigh','Coxa (cm)'],['arm','Braço (cm)'],['abdomen','Abdômen (cm)']].map(([n,l])=><div className="field" key={n}><label>{l.toUpperCase()}</label><input name={n} type="number" step="0.1" min="0"/></div>)}</div><button className="primary-btn full" style={{marginTop:16}}><PlusIcon/>Salvar medição</button></form></div></div>}
  </>
}
